<?php
require __DIR__.'/orders-workflow.php';
$wpdb->fail_payment=false;
$quote=array_merge($base,['requestKey'=>'00000000-0000-4000-8000-000000000101','status'=>'Orçamento','deposit'=>0,'validUntil'=>'2026-09-30']);
$q=call_api('orders','POST',$quote);$id=$q['id'];
yes($q['balance']===90 && $q['validUntil']==='2026-09-30','Validade e valor do orçamento');
rejected(fn()=>call_api('payments','POST',array_merge($pay,['amount'=>10,'requestKey'=>'00000000-0000-4000-8000-000000000102']),['id'=>$id]));
rejected(fn()=>call_api('order','PUT',array_merge($quote,['status'=>'Em Produção','version'=>1]),['id'=>$id]));
rejected(fn()=>call_api('approve','POST',['version'=>99],['id'=>$id]));
$filters=['page'=>1,'from'=>null,'to'=>null,'status'=>null,'q'=>null,'scope'=>'quotes'];
yes(call_api('orders','GET',[],$filters)['total']===1,'Filtro de orçamentos no banco');
$before=(int)$wpdb->get_var('SELECT COUNT(*) FROM test_ygprint_orders');
$a=call_api('approve','POST',['version'=>1],['id'=>$id]);
yes($a['id']===$id && $a['status']==='Em Produção' && $a['approvedQuote']['status']==='Orçamento','Aprovação mantém número e proposta original');
yes((int)$wpdb->get_var('SELECT COUNT(*) FROM test_ygprint_orders')===$before,'Aprovação não duplica');
yes(call_api('approve','POST',['version'=>1],['id'=>$id])['version']===2,'Repetir aprovação não altera versão');
yes((int)$wpdb->get_var("SELECT COUNT(*) FROM test_ygprint_audit WHERE action='approve'")===1,'Um evento de aprovação');
yes(call_api('orders','GET',[],$filters)['total']===0,'Aprovado sai da lista de orçamentos');
$filters['scope']='orders';yes(call_api('orders','GET',[],$filters)['total']===2,'Aprovado entra em pedidos');
rejected(fn()=>call_api('order','PUT',array_merge($a,['requestKey'=>$quote['requestKey'],'status'=>'Orçamento']),['id'=>$id]));
rejected(fn()=>call_api('order','PUT',array_merge($a,['requestKey'=>$quote['requestKey'],'status'=>'Entregue']),['id'=>$id]));
$ready=call_api('order','PUT',array_merge($a,['requestKey'=>$quote['requestKey'],'status'=>'Pronto para Retirada','clientName'=>'Alterado']),['id'=>$id]);
yes($ready['approvedQuote']['clientName']==='Cliente','Proposta aprovada preservada em edição');
$done=call_api('order','PUT',array_merge($ready,['requestKey'=>$quote['requestKey'],'status'=>'Entregue']),['id'=>$id]);
yes($done['status']==='Entregue','Fluxo de entrega');
$expired=call_api('orders','POST',array_merge($quote,['requestKey'=>'00000000-0000-4000-8000-000000000103','date'=>'2026-09-01','validUntil'=>'2026-09-23']));
rejected(fn()=>call_api('approve','POST',['version'=>1],['id'=>$expired['id']]));
$refused=call_api('order','PUT',array_merge($expired,['requestKey'=>$quote['requestKey'],'status'=>'Recusado']),['id'=>$expired['id']]);
rejected(fn()=>call_api('approve','POST',['version'=>$refused['version']],['id'=>$refused['id']]));
$report=call_api('reports','GET',[],['from'=>'2026-09-01','to'=>'2026-09-30']);yes($report['outstanding']===150,'Recusados não entram no saldo a receber');
echo "OK: filtros, validade, conflitos, aprovação idempotente, pagamentos após aprovação, proposta preservada, entrega e recusa.\n";
